/**
 * ...
 * @author Liadri
 */
package classes.Scenes.Areas.Caves 
{
	import classes.*;
	import classes.internals.*;
	import classes.GlobalFlags.kFLAGS;
	import classes.Scenes.UniqueSexScenes;

	public class CaveWyrmScene extends BaseContent
	{
		public var uniquuuesexscene:UniqueSexScenes = new UniqueSexScenes();
		
		public function CaveWyrmScene() 
		{
		}
		
public function berserkingCaveWyrmEncounter():void {
	clearOutput();
//	spriteSelect(32);
	if (rand(3) == 0) flags[kFLAGS.HERM_CAVE_WYRM] = 1;
	else flags[kFLAGS.HERM_CAVE_WYRM] = 0;
	outputText("As you wander the cave you are suddenly surprised as a shimmering neon blue light rush at you at increasing speed. Before you can figure out what is going on a bloodcrazed lizard "+(flags[kFLAGS.HERM_CAVE_WYRM] > 0 ?"herm":"girl")+" with a pair of war axe charge at you her fluorescent eyes glimmering with uncontained rage.\n\n");
//	if (flags[kFLAGS.CODEX_ENTRY_] <= 0) {
//		flags[kFLAGS.CODEX_ENTRY_] = 1;
//		outputText("<b>New codex entry unlocked: Cave Wyrms!</b>\n\n")
//	}
	outputText("You are fighting a Berserking cave wyrm!");
	startCombat(new CaveWyrm());
}

public function winningOverCaveWyrm():void {
	clearOutput();
	menu();
	if (player.hasCock()) {
		addButton(0, "Nope", cleanupAfterCombat);
		if (player.cavewyrmCocks() > 0)
		{
			outputText("Defeated, the Cave Wyrm reels back and falls shoulders-first into the ground. There's a dull smack where she strikes the earth... followed by an odd 'hiss' sound between her legs. Your eyes drop down the busty but fearsome Wyrm's figure to her glistening vagina just in time to see discolored vapors rising from the ground in front of it: she's got acid femcum, and it's turning even the stone under her sex to smoke...! This only turns your acid dripping cock on more...\n\n");
			outputText("Her scaly thighs part a little as she sizes-up your torso and, of course, your own sex. Just how long has she been waiting for this?\n\n");
			addButton(1, "Fuck Her", winningOverCaveWyrmWithCaveWyrmDick);
		}
		else{
			outputText("Defeated, the Cave Wyrm reels back and falls shoulders-first into the ground. There's a dull smack where she strikes the earth... followed by an odd 'hiss' sound between her legs. Your eyes drop down the busty but fearsome Wyrm's figure to her glistening vagina just in time to see discolored vapors rising from the ground in front of it: she's got acid femcum, and it's turning even the stone under her sex to smoke...! You quickly reconsider trying to fuck her...\n\n");
			outputText("... then again, maybe you don't. It's definitely a risk- but since when have you ever played it safe in Mareth? The Wyrm's eyes light up curiously as she sees you eyeing her wet genitals, and something about the twisted grin on her face tells her she'd like you to try. Her scaly thighs part a little as she sizes-up your torso and, of course, your own sex.\n\n");
			addButton(1, "Fuck Her", winningOverCaveWyrmDMelting);
		}
		if (player.pcCanUseUniqueSexScene()) addButton(13, "U. Sex Scenes", uniquuuesexscene.pcUniqueSexScenesChoiceMenu).hint("Other non typical sex scenes.");
	}
	else {
		outputText("You approach the defeated lizard girl intending to punish her for her assault but the drop of precum fuming on the ground like acid next to her cunt tells you that it's a VERY bad idea. Who knows what your ");
		if (player.hasVagina()) outputText("pussy" + (player.hasCock() ?" or ":"") + "");
		if (player.hasCock()) outputText("cock");
		outputText(" might end up like if any of these fluids gets in contact with them. Deciding against it you smash the " + (flags[kFLAGS.HERM_CAVE_WYRM] > 0 ?"herm":"female") + " unconscious instead and get your spoils. The locals will better use her then you would.");
		addButton(0, "Leave", cleanupAfterCombat);
		if (player.pcCanUseUniqueSexScene()) addButton(13, "U. Sex Scenes", uniquuuesexscene.pcUniqueSexScenesChoiceMenu).hint("Other non typical sex scenes.");
	}
}	
public function winningOverCaveWyrmDMelting():void {
	clearOutput();
	outputText("There's a busty, scaly " + (flags[kFLAGS.HERM_CAVE_WYRM] > 0 ?"futa":"female") + " in front of you with a literally smoking-hot pussy just itching to take you whole. Either because you're terribly brave or just too horny- you shed your clothes from your body at a brisk pace, both eager and apprehensive of laying the Cave Wyrm with no protection... yet your firm phallus bobs and stands-up to attention even in the cool cavern air, clearly eager to take-on the challenge of her acid femcum.\n\n");
	outputText("Your knees graze across her lower thighs as you kneel over her, dropping to get in position- ... but you feel her smooth, scaly legs scraping on your outer shins as she scoots-forward and bucks up as if to meet you. \"<i>What a stupid " + player.mf("boy","girl") + ". You've seen my acid, but you're gonna fuck me anyway?</i>\" She asks, even as she nudges closer to you. Your bodies are almost entwined now- and suddenly, you feel a push from behind-!\n\n");
	outputText("Her broad tail is now laid across your whole lower back, pushing into the curve of your spine while bucking the thick part of her muscular newt-like tail against your butt-cheeks. The motion forces you into her clawing embrace: your penis " + (flags[kFLAGS.HERM_CAVE_WYRM] > 0 ?"bumps-into and grinds up her own, but ":"") + "quickly approaches the thick labia of her acid-leaking sex. Her hips slowly buck-up, almost touching her vagina to your bare penis...!\n\n");
	outputText("You hesitate for a moment, but you realize it's too late; you're much too hard, and she's got five limbs holding you in place for a mating she seems to want very much... \"<i>Come on, don't be a coward. Do it!</i>\" She goads, obviously reveling in your apprehension. You eye her body once more, even while you resist her tail's pushes towards her sex- she's got a broad, busty body with all kinds of curves. But she's taut and strong too- with a belly that begs to be full of fertilized eggs");
	outputText(". " + (flags[kFLAGS.HERM_CAVE_WYRM] > 0 ?"There's something erotic about how her hard, slick cock bounces in the open air too. ":"") + "Somewhere your hesitation gets lost against your heated libido.\n\n");
	outputText("The Cave Wyrm's mouth opens into a surprised 'O' as you grip the base of your swollen phallus and lower it to glide-down her lips, where you already feel a suspicious tingling wherever her fluids touch your cockhead. But you don't hesitate again: aided by her tail pushing into your lower back, your girth eases steadily between her thick labia to vanish inside of her slick, glowing vagina. Immediately, thick muscles inside her vaginal canal grip onto your member and undulate along it, encouraging you deep into her- you're hilted in seconds.\n\n");
	outputText("It feels wonderful- hot flesh squeezes your member like a vice of molten ambrosia, but reality returns as a terrifying sound fills your ears: there's a loud 'hiss' coming right from your joined sexes, where your engorged penis is stuck balls-deep in her greedy vagina. You feel the acidic bath of her caustic cum covering and working your tender shaft. Hell, you can even see it- your skin has turned red, and feels like it's gotten thinner all down your dick. Cold sweat beads on your brow and your eyes go wide at the sight of your now bright-red member as it bucks helplessly in-and-out of the horny Wyrm's hazardous sex.\n\n");
	outputText("You let out a slow moan. It's not a manly grunt- it's a pure, solemn utterance of raw pleasure. Across your dick, you feel burning pleasure tingling through your every nerve- and far deeper than during any other sex you've had. You try to clutch onto the Wyrm's hips, but your fingers tremble and your hold on her is weak... \"<i>Hah~ ah, this'll be good.</i>\" She utters with satisfaction, before hooking one ankle behind your ass and leaning back. With one palm on the ground, she bucks on-and-off your crotch, leaking droplets of acid off your joined sexes.\n\n");
	outputText("Somehow- it feels wonderful! There was a hot pain in your skin for a moment, all over your dick- but now it's gone, and you guess your sensitivity must be twenty times what it was before. You start bucking with her, intent on fucking her proper- yet her eyes meet yours with a mocking gaze; there's both unkindness and satisfaction about her expression, which makes you nervous. \"<i>Melting some of your skin makes your pecker way more sensitive. Can you handle it? Is it too much!?</i>\" She asks, suddenly working up into a fervor; it's like she's gone berserk again!\n\n");
	outputText("Your bodies roll in a lewd union across the cavern floor, your bodies bucking with each other. Her thighs scrape across your sides constantly, your crotches joined for minutes as you fuck each other with wild, lusty abandon. You're soon a sweaty mess, but you manage to keep up with the Wyrm" + (flags[kFLAGS.HERM_CAVE_WYRM] > 0 ?", whose cock bounces above or grinds against your belly in sloppy strokes with your bucks, thrusts and twists together as mates":"") + ". It's raw, primal sex... and true to her words, the pleasure you feel is far more than it could ever normally be: ");
	outputText("pleasure radiates along your dick's insides, resulting in throbs of euphoria. Only a tiny burning sensation reminds you that you're dick-deep in acid.\n\n");
	outputText("Two arms scoop-around your chest and hug you to her bosom, before the Wyrm twists and raises-up to plant herself on top of your crotch. The cool cavern stone floor on your back feels good- but so does the hot, messy-wet vice of her sex around your hilt. Looking down, you see yourself balls-deep in her plump pussy still, her tail thrashing behind her as she makes slow bucks up and down- ... your breath catches, and your nerves all but tremble. You're about to cum!\n\n");
	outputText("Scaled fingers lay-down and splay across your chest as she presses her crotch into yours: your dissolving dick makes huge throbs inside of her, blowing-out the thickest load you've shot in months. Even with her acid- you cum enough semen past her cervix and into her womb that she's sure to fertilize at least a few of her eggs. But as your member spurts and swells, you begin to feel a sharp pain all-over your penis. It makes you jerk-up and spasm at first, then it becomes a flare of searing anguish alike to having your dick buried in a bath of razor-blades and broken glass. You've got to pull out!-\n\n");
	outputText("-but you can't, and you won't: you were a fool to start this, but you were more foolish to let her get on top of you... \"<i>Now I need more than your cum. Just be still and take it like a man!</i>\" She cries out; once your mate just minutes ago, the lusty Wyrm is now your tormentor. Tears well up in your eyes as you feel true pain thud through your nerves like the sound of a huge bell chiming near you. Your teeth grit and grind, as you truly feel your entire dick melting to liquid inside of her. You can still feel some of the wet-and-hot pleasure you had earlier inside of her, but it's far less now and it's clear you paid a price to enjoy it.\n\n");
	outputText("She huffs and groans; you're not sure how many times she came or if she's been cumming for minutes already, but ecstasy peaks on her face before she smiles and leans back, palms now on your knees. \"<i>Haaah~</i>\" She groans, wiggling her hips into your crotch- ... you don't actually feel much in her now, just a tiny tingle of pleasure before an eerie chill sweeps your groin. \"<i>Ah- good. Finally. Too bad I can only use a mate like this once...</i>\" She says, before pushing-up off your thighs. You immediately look with panic to where your sexes were joined-\n\n");
	outputText("-there's just a wet smear of cum and glowing femcum where her thick-lipped pussy rises off your crotch. Strands of your shared fluids still connect her crotch to yours... but they snap as she stands up, and you realize something: your dick is gone, totally dissolved inside of her acidic pussy while you had sex with her. She looks like she's about to leave- but she stops when she sees the fear and shock in your eyes.\n\n");
	outputText("She just shrugs. \"<i>You were warned, you know? I needed to melt your dick to feed my eggs. It's gone, but at least you'll probably make a hatchling.</i>\" She says- ... some effort to console you, maybe, but you still stare down at your dickless crotch with shrill surprise. Both pain and pleasure echo through your nerves. You hear her footsteps carrying her away, and by the time you look, the Cave Wyrm is gone.\n\n");
	if (!player.isGargoyle()) {
		if (player.cocks.length > 1) player.removeCock(0, 1);
		else player.killCocks(1);
	}
	player.sexReward("vaginalFluids");
	cleanupAfterCombat();
}

public function winningOverCaveWyrmWithCaveWyrmDick():void {
	clearOutput();
	outputText("There's a busty, scaly " + (flags[kFLAGS.HERM_CAVE_WYRM] > 0 ? "futa" : "female") + " in front of you with a literally smoking-hot pussy just itching to take you whole. You shed your clothes from your body at a brisk pace, eager of laying the Cave Wyrm... your firm neon blue phallus bobs and stands-up to attention even in the cool cavern air, clearly eager to take-on this female.\n\n");
	outputText("Your knees graze across her lower thighs as you kneel over her, dropping to get in position- ... but you feel her smooth, scaly legs scraping on your outer shins as she scoots-forward and bucks up as if to meet you. \"<i>Geeze if only you males were more common I would not spend half of my days chasing after random strangers in the tunnels.</i>\" She tells, even as she nudges closer to you. Your bodies are almost entwined now- and suddenly, you feel a push from behind-!\n\n");
	outputText("Her broad tail is now laid across your whole lower back, pushing into the curve of your spine while bucking the thick part of her muscular newt-like tail against your butt-cheeks. The motion forces you into her clawing embrace: your penis " + (flags[kFLAGS.HERM_CAVE_WYRM] > 0 ? "bumps-into and grinds up her own, but " : "") + "quickly approaches the thick labia of her acid-leaking sex. Her hips slowly buck-up, almost touching her vagina to your bare penis...!\n\n");
	outputText("She's now got five limbs holding you in place for a mating she seems to want very much... \"<i>Come on, just fill me with your seed already, I know you want it</i>\" She goads, obviously reveling in your desire. You eye her body once more, even while you resist her tail's pushes towards her sex- she's got a broad, busty body with all kinds of curves. But she's taut and strong too- with a belly that begs to be full of fertilized eggs");
	outputText(". " + (flags[kFLAGS.HERM_CAVE_WYRM] > 0 ? "There's something erotic about how her hard, slick cock bounces in the open air too. " : "") + "Somewhere your hesitation gets lost against your heated libido.\n\n");
	outputText("The Cave Wyrm's mouth opens into a surprised 'O' as you grip the base of your swollen phallus and lower it to glide-down her lips, where you already feel a suspicious tingling wherever her fluids touch your cockhead. But you don't hesitate again: aided by her tail pushing into your lower back, your girth eases steadily between her thick labia to vanish inside of her slick, glowing vagina. Immediately, thick muscles inside her vaginal canal grip onto your member and undulate along it, encouraging you deep into her- you're hilted in seconds.\n\n");
	outputText("It feels wonderful- hot flesh squeezes your member like a vice of molten ambrosia, but reality returns as a terrifying sound fills your ears: there's a loud 'hiss' coming right from your joined sexes, where your engorged penis is stuck balls-deep in her greedy vagina. You feel the acidic bath of her caustic cum covering and working your tender shaft. Hell, you can even see it- your skin has turned red, and feels like it's gotten thinner all down your dick. You sigh in delight at the sight of your now acid drenched member as it bucks relentlessly in-and-out of the horny Wyrm's hazardous sex. Having cave wyrm cock is conveniant because if you werent immune to your partners secretions you would be loosing it right now.\n\n");
	outputText("You let out a loud mown of delight at the raw pleasure. Across your dick, you feel oozing pleasure tingling through your every nerve- and far deeper than during any other sex you've had. You try to clutch onto the Wyrm's hips, but your fingers tremble and your hold on her is weak from the bliss... \"<i>Hah~ ah, this'll be good.</i>\" She utters with satisfaction, before hooking one ankle behind your ass and leaning back. With one palm on the ground, she bucks on-and-off your crotch, leaking droplets of acid off your joined sexes.\n\n");
	outputText("Somehow- it feels wonderful! Her fluids is coating all over your dick- acting as a mild aphrodisiac and you guess your sensitivity must be twenty times what it was before. You start bucking with her, intent on fucking her proper. \"<i>You lucky your dick match my cunt else it would be melting right now most males aren't fortunate enought to have a cock that is resiliant to acid. This said my acid acts like a mild aphrodisiacs for you males wich naturaly makes the sex twice as wilder, think you can handle the heat?</i>\" She asks, suddenly working up into a fervor; it's like she's gone berserk again!\n\n");
	outputText("Your bodies roll in a lewd union across the cavern floor, your bodies bucking with each other. Her thighs scrape across your sides constantly, your crotches joined for minutes as you fuck each other with wild, lusty abandon. You're soon a sweaty mess, but you manage to keep up with the Wyrm" + (flags[kFLAGS.HERM_CAVE_WYRM] > 0 ? ", whose cock bounces above or grinds against your belly in sloppy strokes with your bucks, thrusts and twists together as mates" : "") + ". It's raw, primal sex... and true to her words, the pleasure you feel is far more than it could ever normally be from a defrent partners cooch. This cock is made to fuck wyrms like her: ");
	outputText("pleasure radiates along your dick's insides, resulting in throbs of euphoria. The drooling acid from her snatch onto your tights only serves to make you fuck her harder.\n\n");
	outputText("Two arms scoop-around your chest and hug you to her bosom, before the Wyrm twists and raises-up to plant herself on top of your crotch. The cool cavern stone floor on your back feels good- but so does the hot, messy-wet vice of her sex around your hilt. Looking down, you see yourself balls-deep in her plump pussy still, her tail thrashing behind her as she makes slow bucks up and down- ... your breath catches, and your nerves all but tremble. You're about to cum!\n\n");

	outputText("Scaled fingers lay-down and splay across your chest as she presses her crotch into yours: your dick makes huge throbs inside of her, blowing-out the thickest load of neon acidic cum you've shot in months. Because of her acid- you cum enough semen past her cervix and into her womb that she's sure to fertilize at least a few of her eggs. This your partner is far from done and as you reach your second wind she catch up and resume bucking her hips.\n\n");
	outputText("\"<i>I need more of your cum. theres no telling for when ill get another mate who can take me on like this!</i>\" She cries out; You still feel the same wet-and-hot pleasure you had earlier inside of her and it seems you won't stop feeling it for a while as your partner relentlesstly attempt to milk your seed.\n\n");
	outputText("She huffs and groans; you're not sure how many times she came or if she's been cumming for minutes already, but ecstasy peaks on her face before she smiles and leans back, palms now on your knees. \"<i>Haaah~</i>\" She groans, wiggling her hips into your crotch as you reach your own orgasmYour member spurts and swells keeping on filling the horny cave wyrm cunt for whats its worth of your glowing seed until her belly balloons out with the sheer volume of your neon blue cum. You can actualy see your cum from inside her stomach as it cause her bellow to glow with the characteristic neon blue of your fluids. \"<i>Ah- good. Finally. Normaly most of my mate dicks melt but yours is thankfully made for this</i>\" She says, before pushing-up off your thighs.\n\n");
	outputText("She just shrugs. \"<i>Well the bad news is that I still need to get nourishment for the eggs so I can't stay with you, but at least you'll probably make a few hatchling.</i>\" She says before lifting up. While your still recovering from the subsequant orgasms you hear her footsteps carrying her away, and by the time you look, the Cave Wyrm is gone.\n\n");
	player.sexReward("vaginalFluids");
	outputText("\n\nThe residual effect of her vaginal acid seems to have enhanced your member sensitivity as well as your libido by a notch.");
	player.lib+=5;
	player.sens++;
	cleanupAfterCombat();
}

public function loosingToCaveWyrm():void {
	clearOutput();
	outputText("You fall to the ground, defeated and look for a way to escape the she-maniac but a jet of blue fire on your right reminds you that if you attempt anything she will roast you alive, so you turn back to face your assailant.\n\n");
	outputText("The lizard girl grin as her pussy slowly begins to drool a clear drop of blue fluid. You are keenly aware of what is about to happen as she casually walks to you and begin to remove her gear.\n\n");
	if (player.hasCock()) outputText("\"<i>Pathetic… I was hoping for a mighty warrior not a welp unworthy of fertilising my eggs. You know what happens to losers down in these caves? Because you are about to find out the hard way. I have been looking for someone to sooth my itches with for hours. That said your unworthy of me as a female so you're going to use your cute little tongue instead.</i>\"\n\n");
	else {
		outputText("As she gets to you to have  a check at her catch she sigh disappointed as she realise you have no penis.\n\n");
		outputText("\"<i>You know what happens to losers down in these caves? Because you are about to find out the hard way. I have been looking for someone to fuck with for hours but since you have no cock to do it you're going to use your cute little tongue instead.</i>\"\n\n");
	}
	outputText("She grabs you by the hair and pulls you toward her cunt.\n\n");
	outputText("\"<i>Get to it and don’t make me repeat myself twice!</i>\"\n\n");
	outputText("You get the message and let your tongue past your lips into her fold. For some reason as your tongue comes into contact with the juices of the lizard girl it begins to throb uncontrollably until at some point it's dye the same color as the radioactive blue fluid its coated into. Something takes hold of your mind there and urges you to finish the job. You need more, you want more of that fluid!\n\n");
	outputText("\"<i>Ah yes that's a good slut! Lick me clean.</i>\"\n\n");
	outputText("She shove you closer filling your nose full on that pussy scent and you outright lose it eating her out in earnest as you try to fill your mouth with this nectar of hers. By now your tongue feels sensible like a clit yet at the same time you manage to reach corners of the woman pussy you never could before proding all the way up to her womb.  Eventually the reptilian woman cry in orgasm as her pussy flood your face with your juice reward, you mouth gladly swallowing as much of it as you can before the warrior finally knock you out satisfied with your handiwork.\n\n");
	outputText("When you wake up she is already gone but at least she left your equipment in a tidy pile next to you.\n\n");
	cleanupAfterCombat();
}
public function loosingToHermCaveWyrm():void {
	clearOutput();
	outputText("You fall to the ground defeated and look for a way to escape the she-maniac but a jet of blue fire on your right reminds you that if you attempt anything she will roast you alive, so you turn back to face your assailant.\n\n");
	outputText("The lizard-herm grin as her 13 inch cock, already erect, begins to dribble precum. You are keenly aware of what is about to happen as she casually walk to you and begin to remove her gear.\n\n");
	outputText("\"<i>You know what happens to losers down in these caves? Because you are about to find out the hard way. I have been looking for someone to fuck with for hours.</i>\"\n\n");
	if (player.hasVagina()) {
		outputText("Before you can do anything, the lizard herm forces you to the ground, stripping you of your gear as she grabs your arms and pull your legs apart. You try and keep them closed but she is already blocking them with her body. She however swiftly remind you who is in charge.\n\n");
		outputText("\"<i>Don’t resist and I perhaps won't need to scorch your face, got it bitch?</i>\"\n\n");
		outputText("You comply, horrified, as she begins to slowly tease your pussy with her tip. Before you get any chance to react she shove her entire length in, making your eyes go wide. Warm precum slowly leak from her cock into your cunt and to your surprise you vaginal walls begins to mold and accomodate the reptilian prick as the warm fluid smears against them. You look down to your pussy in time to notice the lips have taken on a weird blue glow. Warmth spread from it to the rest of your body");
		if (player.hasBreasts()) outputText("your nipple hardening at the thought of letting that powerful herm mate you");
		outputText(". She moves her face down right next to yours and give it a playful lick with her long, neon blue, glowing lizard tongue.\n\n");
		outputText("\"<i>Like the gift of my precum girl? Down here it's eat or be eaten and I can’t afford to be picky. That said you have one great pussy! Put some heart into it and I’ll perhaps get you off too, maybe even impregnate you if you are very lucky as deserves a proper warrior maiden.</i>\"\n\n");
		outputText("The lizard herm begin to pant in delight as she forcefully pull in and out of you. You moan as her length works your [vagina], holding her tight to you by wrapping your arms around her body in a lust addled hug. You cry in ecstasy as she finally reach her orgasm filling your warm thirsty cunt full of glowing blue seed. Thankfully, you lose consciousness just as she ready for round two.\n\n");
		outputText("When you wake up she is already gone but at least she left your equipment in a tidy pile next to you.\n\n");
	}
	else {
		outputText("Before you can do anything, the lizard herm forces you into the ground, stripping you of your gear as she pushes you on all fours and grab your [ass]. You try to crawl away but she swiftly remind you who is in charge by breathing fire just ahead of you.\n\n");
		outputText("\"<i>Don’t resist and perhaps I won't need to scorch your back, got it buttslut?</i>\"\n\n");
		outputText("You comply, horrified, as she began to slowly align herself with your pucker. Before you get any chance to react she shove her entire length in, making your eyes go wide. Warm precum slowly leak from her cock into your ass and to your surprise you hole begins to loosen on its own as the warm fluid spreads against its walls. She move her face down right next to your ear and give it a playful lick with her long, neon blue, glowing lizard tongue.\n\n");
		outputText("\"<i>Now that's what I call a hole! Put some heart into it and I'll perhaps get you off too.</i>\"\n\n");
		outputText("The lizard herm begin to pant in delight as she forcefully pull in and out of you, slapping your [ass] at about every five thrusts. By the time she finally reach her orgasm, filling your abused hole full of glowing blue seed, your butt cheeks are imprinted red with her hand shape. Thankfully, you lose consciousness just as she ready for round two.\n\n");
		outputText("When you wake up, she is already gone and your ass is still leaking with bluish fluorescent cum but at least she left your equipment in a tidy pile next to you.");
	}
	player.sexReward("cum");
	cleanupAfterCombat();
}
public function loosingToCaveWyrmDMelting():void {
	clearOutput();
	outputText("You're not sure when it happens- but you lose, and your skin cries-out in pain from the many cuts left on you by the Wyrm's frenzied assault. Many small red lines cross your body... and you just don't have the strength to get back up. You gaze up on your attacker, the Wyrm's scaly breasts bounce atop her bosom with heaves and swells of her quickened breath. Though they're not large by Mareth's standards- there's a lovely, perky jiggle about them with every one of the fierce warrior's exhales.\n\n");
	outputText("A clawed foot bucks-forward into your sternum, and the Wyrm holds you down on the ground by a press of her heel. \"<i>Hrn- hmmn...</i>\" She growls, almost snarling, if not for her low tune. Her nostrils flare as she sniffs the air. Moments later, she drops her other foot to tear through your clothes and expose your phallus. You're soft still, but... as you look up her thick, curvy legs- especially on those broad curvy thighs joined to the Wyrm's juicy egg-bearing hips- you can't help but slowly and surely stiffen to a hard, swollen erection.\n\n");
	outputText("Even as you squirm and try to escape her capture, your seemingly happy dick throbs and sways in the air, standing straight up. One of the Wyrm's scaly toes caresses your hard dick with slow strokes along its side... \"<i>You know what? I think you'll do nice for a fuck.</i>\" She says, before tossing back her axes. They clang loudly back across the cavern floor behind her... far from her reach, and now her clawed hands open-and-close in front of her while a look of cartoonish mischief crosses her frenzied face.\n\n");
	outputText("Bending over, the Wyrm falls to her knees to get a better look at your dick. " + (flags[kFLAGS.HERM_CAVE_WYRM] > 0 ?"Her own penis is bobbing and swaying half-erect in the open air the whole time, even dripping excess bits of precum while she grips the base of your dick and gropes-along it with both her hands. " : "") + "Her palms are scaly and her tough fingers don't feel good- but you get even harder, excited by her apparent lust and naked bust.\n\n");
	outputText("Leaning into your crotch, the Wyrm opens her mouth and pushes her tongue into the base of your dick, before dragging up its whole underside in a long, wet lick. It makes a nasty wet noise, one you can only register as naughty... \"<i>Hah! It's so hard already. You must really want to get melted, huh little guy?</i>\" She asks before, despite her disturbing speech, making an affectionate nuzzle into your much too eager phallus. You're left terrified at the mention of melting, but what can you do...? Your whole body is sore and it wouldn't take a second for one of those strong Wyrm-claws to rip your throat out.\n\n");
	outputText("Despite your fear and tension, your hopes rise as you see the Wyrm's hips rais. She scoots into your lap, and now you get a good look at what's under her bobbing-and-swaying dick: huge, plump pussy-lips frame her thick vaginal opening, which drips glowing blue femcum that already covers her slimy sex. You can smell the pungent odor of her bare, exposed genitals now, up this close. It's natural- earthy, sweaty, a little 'fishy' and raw. But somehow it's not bad, you feel your arousal climb and boil as she drops down to mount you, so hard you almost forget her comment about melting something.\n\n");
	outputText("The Wyrm is taking it slow: first, her heavy yet wonderfully curvy thighs clasp onto your hips before spreading to drop her fat vulva towards your cockhead. Visibly, the azure colored opening of her plump pussy opens, squeezes and flexes, ready to wring your dick dry with an almost scary amount of muscular power. Her blue juices drop down and glimmer with bioluminescence as her vaginal canal winks, but as the droplets and wet beads hit your cockhead, you're immediately met with a bizarre sensation.\n\n");
	outputText("You feel a sharp tingling sensation on the tip of your cockhead before you actually hear it next. There's a loud, long 'hiss' sound... there's a lot of pussy juice coming out of the Cave Wyrm, enough that it's gradually spilled over your whole phallus now. And the hissing noise goes wherever it covers your dick. Your eyes widen and your heart sinks as you watch a thin, misty smoke rise off your dick where her fluids begin dissolving the skin on your penis, her vaginal juices are acidic!\n\n");
	outputText("Soon, your whole dick is red and inflamed, and almost all the skin on it is gone. Your teeth grit and you whine at an incredible sensation: it's so cold! All around your dick, the air is suddenly freezing and harsh, like there's bits of hail blowing across your naked penis. Your still-throbbing, badly-swollen penis is a tomato-red color now... but all of it vanishes as, with a languid yet certain push, the Cave Wyrm slowly drops her pussy's cleft onto your penis and pops its reddened cockhead into her sex. ");
	outputText("\"<i>Aah, first bite's the best part...</i>\"  She says breathlessly, while her back bends away from you and her hands drop to fall palms-down atop your knees. Her eyes shut while she bucks her hips down, and you can feel the incredible strength of her vaginal muscles as they envelop more of your phallus in dropping vices of rippling ring-like ridges of strong squeezes and soft, molten wet flesh with a texture more pleasant than any silk.\n\n");
	outputText("You expect it to hurt badly... but actually, maybe because you've got less skin on it, your bare dick surprises you with a bright cascade of white hot pleasure that rumbles through your nerves, starting in the core of your penis but quickly radiating out to surge and tingle throughout your whole dick- which, doesn't actually seem to be melting...? Your breath catches and your fingers are trembling. You accidentally bite your lip, and your heart pounds, your thoughts are hard to hold onto, and quickly your brain's getting blasted with an impossible pleasure feedback. You shiver and quiver with the slightest motion of the Wyrm's hips!\n\n");
	outputText("She hilts you in her, happy to grind her wet and scaly crotch against yours. It feels good, she's firm and strong, but her inner vagina is full of very soft blue flesh, the ridges and powerful muscles of which are absolutely overjoyed to grip, massage and milk you with merciless abandon. You have to pull your head back and force yourself to breathe as your senses are overwhelmed, your dick's so sensitive you feel a buzzing tension in your eyelids, your fingers, everywhere! Your whole body is spasming under the busty big hipped lover on top of you, whose own dick is bouncing at full hardness while she rides yours with a happy, though ");
	outputText("mischievous grin. Sometimes you manage to see tiny glimpses of the acid-burned red dick of yours that's stuck in her, reminding you that you're in danger...\n\n");
	outputText("You quiver and rise up to try and stop her, and not because you're afraid of having your penis trapped in her acid bath, but because instinctively your body's being overwhelmed with sensation. Every nerve in your whole dick must be getting stimulated, but she catches your hands as they go for her hips, and leans heavily down on you to totally arrest her efforts. You hear the wet smacks, slurps and squelches of her thick lipped pussy squishing down on your whole dick, her plump and powerful labia clinging onto your phallus every time she rises as if those fat pussylips just don't want to let go of you.\n\nYou... can't resist anymore. ");
	outputText("Your expression breaks out into a dizzy, delighted grin. Your breathing comes in a gradually quickened fervor, as you feel an ambrosia dripping down on your brain like hot syrup; warm, rising fullness blows through your overstimulated phallus, and you feel wonderful as pump all your semen into the Cave Wyrm. It's so much, you're sure that you're out. But you keep spurting away... ten seconds, fifteen, twenty...? It's maybe a minute before your orgasm ends, the longest you've ever enjoyed. Your penis feels hard and soft at the same time, all but crushed by soft, hot wet flesh, like a thousand angels are licking it in earnest.\n\n");
	outputText("But then... your dick starts to feel softer. It feels wrong. Your happy, post orgasmic afterglow ends, and you open your eyes to get a look at your joined bodies: you're a sweaty mess, and the busty Wyrm is still senselessly grinding into you, but you can see your dick starting to bend as it's inside her and you can't help but feel afraid. Her eyes, bright, blue and glowing, drop to look on yours with an animalistic fury. \"<i>You can tell, huh?</i>\" She asks, grinning wider, and showing you her sharpened smile. ");
	outputText("\"<i>Your dick is really going to melt in here. I'll take it just like I took your cum. That's the only way I can breed...</i>\" She says, before powerful hands reach out to grasp your shoulders, and the Cave Wyrm's face slowly drops to hover inches from yours.\n\n");
	outputText("She's staring into your eyes with unkindness as much as interest. It's clear to you now that she's done it before, and she very much wants to do it to you. \"<i>Now be still and give me that dick!</i>\" She cries out, before mashing her crotch down on yours as hard as she can. You can feel her labia compress and tighten around your ring, and soon you hear a terrible 'hiss' again... and you feel it, at the same time. Your molars grit and grind and your eyelids shoot wide. You're screaming, but you don't even realize it, nerves that once howled in pleasure now shriek in pain, as they're slowly melted away in the horny Wyrm's acidic vagina.\n\n");
	outputText("Your 'lover' takes it much better than you do. Her tongue helplessly slips out from her mouth and falls on your forehead, quivering with the rest of her body as she rocks with orgasm...! Her hips try to buck into you, but your bodies are already conjoined, and the motion only pushes you a part of the ways up the cavern wall behind you. Her hot breath actually gets your hair wet as she huffs, moans and groans, the sounds of her pleasured exhales almost drowning-out your sharp cries of pain and lament.\n\n");
	outputText("Then... she hugs you, holding you against her bosom. You slowly calm down, but you're still in shock, and your skin is paled. You feel a final tingle of something not quite pain nor pleasure, before there's only a cold and nauseating sensation on your skin where you used to have a dick. \"<i>Mn~ finally...</i>\" She murmurs, her whole body slowly undulating up-and-down to somehow stroke you. Your legs, your sides, your face... her fingers, legs and tail all but molest you as you rest there, tormented and shaken in her scaly embrace.\n\n");
	outputText("You hear a 'pop' as her hips rise off yours. A long, ropey strand of her vaginal juices and your own cum connects from her pussy's now-swollen opening to your now dickless crotch. There's just smooth skin where your penis was and your body aches around it with an eerie, cold sensation that is simply... wrong. Her finger under your chin draws your attention away from your loss and then to her callous yet enraptured visage. ");
	outputText("\"<i>Hey, just don't focus on it. You'll definitely make me a hatchling now, and I know you're definitely not a virgin anymore.</i>\" She says in some shallow effort to comfort you. Her hands push on your chest as she stands-up, then walks a ways backwards to pick up her axes.\n\n");
	outputText("She turns and flashes you a grin before waving one of her axe holding hands. \"<i>Bye!</i>\" She says with satisfaction, before setting off at a much slower pace towards the inner caves. You now know why these Wyrm women are so sexually frustrated: they can only ever get one release from a single partner... and at a price you now know bitterly. You groan as you pick your sticky and sickly body off the ground, grimacing as you pull your clothes back over your dickless crotch and set-forward just to leave this place...\n\n");
	if (!player.isGargoyle()) {
		if (player.cocks.length > 1) player.removeCock(0, 1);
		else player.killCocks(1);
	}
	player.sexReward("vaginalFluids");
	cleanupAfterCombat();
}
		
	}
}