// I'm moving all the flag const definitions out of each individual file in preparation for replacing them altogether.
const AKBAL_TIMES_BITCHED:int 					= 902;
const AKBAL_BITCH_Q:int 						= 903;
const AMILY_VISITING_URTA:int 					= 346;
const AMILY_NEED_TO_FREAK_ABOUT_URTA:int 		= 347;
const AMILY_MET:int 							= 35; //  (0 = not met, 1 = met)
const AMILY_VILLAGE_ENCOUNTERS_DISABLED:int 	= 36; // 1=true,44=village button
const AMILY_GROSSED_OUT_BY_WORMS:int 			= 37; // 1=freaked out
const AMILY_AFFECTION:int 						= 38; //  (< 15 = low.  In between = medium. 40+= high affect)
const AMILY_OFFER_ACCEPTED:int 					= 39; //  (1 = true, 0 = not yet)
const AMILY_BIRTH_TOTAL:int 					= 40; //
const AMILY_INCUBATION:int 						= 41; //   0 = not pregnant, otherwise hours till birth 168
const AMILY_FUCK_COUNTER:int 					= 42; //
const AMILY_FOLLOWER:int 						= 43; //
const AMILY_VILLAGE_ACCESSIBLE:int 				= 44; //
const AMILY_WANG_LENGTH:int 					= 45; //
const AMILY_WANG_GIRTH:int 						= 46; //
const AMILY_CUP_SIZE:int 						= 47; // 5-Jan
const AMILY_NIPPLE_LENGTH:int 					= 48; // 0.3-4
const AMILY_HIP_RATING:int 						= 49; // girly-womanly
const AMILY_ASS_SIZE:int 						= 50; //
const AMILY_LACTATION_RATE:int 					= 51; //
const AMILY_CLOTHING:int 						= 52; //
const AMILY_MET_AS:int 							= 158; //
const AMILY_CONFESSED_LESBIAN:int 				= 159; // 1=yes,2=and accepted
const AMILY_TIMES_FUCKED_FEMPC:int 				= 160; //
const AMILY_HERM_TIMES_FUCKED_BY_FEMPC:int 		= 161; //
const PC_TIMES_BIRTHED_AMILYKIDS:int 			= 162; //
const PC_PENDING_PREGGERS:int 					= 163; // 1=yes,2=finished
const AMILY_PC_GENDER:int 						= 164; //
const AMILY_HERM_QUEST:int 						= 165; // 1=amily flipped out, 2=accepted as amily's dad
const AMILY_ALLOWS_FERTILITY:int 				= 166; // 
const AMILY_CORRUPT_FLIPOUT:int 				= 168;
const AMILY_TIMES_BUTTFUCKED_PC:int 			= 419;
const TIMES_FUCKED_AMILYBUTT:int 				= 420;
const AMILY_OFFERED_DEFURRY:int 				= 336; // 1 = Offered to defurry Amily
const AMILY_NOT_FURRY:int 						= 337; // 1 = Amily is no longer a flea-ridden furry who stinks up your carpet.
const AMILY_IS_BATMAN:int 						= 338; // 1 = You turned Amily into a human and then pissed all over her happy thoughts.  She now stalks you from rooftops while buying graphite helmets, utility belts, and a sweet, jetpowered car in the theme of a rat.
const AMILY_INCEST_COUNTDOWN_TIMER:int 			= 436; //1 = timer started, 30 = RIPE FOR INCEST
const AMILY_OVIPOSITED_COUNT:int 				= 629;
const AMILY_OVIPOSITED_COUNTDOWN:int 			= 630;
const AMILY_OVIPOSITION_UNLOCKED:int 			= 631;
const AMILY_TIMES_SWIMFUCKED:int 				= 635;
const AMILY_OWNS_BIKINI:int 					= 636;
const FOLLOWER_HEL_TALKS:int 					=  700; // FOLLOWER_HEL_TALKS
const AMILY_X_IZMA_POTION_3SOME:int 			= 771;
const GIVEN_AMILY_NURSE_OUTFIT:int 				= 775;
const TIMES_MET_ANEMONE:int 					= 453;
const ANEMONE_KID:int 							= 454;
const KID_ITEM_FIND_HOURS:int 					= 455;
const ANEMONE_WATCH:int 						= 456;
const ANEMONE_WEAPON:int 						= 457;
const KID_A_XP:int 								= 756;
const KID_SITTER:int 							= 757; //0 = no sitter, 1 = possible, 2 = doing dat shit
const HAD_KID_A_DREAM:int 						= 758;
const TIMES_IN_BENOITS:int 						= 562;
const BENOIT_AFFECTION:int 						= 563;
const BENOIT_EXPLAINED_SHOP:int 				= 564;
const BENOIT_SUGGEST_UNLOCKED:int 				= 565;
const BENOIT_1:int 								= 567;
const BENOIT_2:int 								= 568;
const BENOIT_3:int 								= 569;
const BENOIT_TALKED_TODAY:int 					= 570;
const BENOIT_TALKED_TO_PROPERLY:int 			= 571;
const BENOIT_EGGS:int 							= 572;
const BENOIT_TIMES_SEXED_FEMPCS:int 			= 573;
const BENOIT_BIRTH_DELAY:int 					= 574;
const BENOIT_WOMB_TALK_UNLOCKED:int 			= 575;
const BENOIT_POST_FIRSTFUCK_TALK:int 			= 576;
const BENOIT_TESTED_BASILISK_WOMB:int 			= 577;
const BENOIT_GENERIC_EGGS:int 					= 632;
const ANTS_PC_FAILED_PHYLLA:int 				= 467;
const ANT_COLONY_KEPT_HIDDEN:int 				= 468;
const PC_READY_FOR_ANT_COLONY_CHALLENGE:int 	= 469;
const PHYLLA_SAVED:int 							= 470;
const MET_ANT_ARENA:int 						= 471;
const ANT_ARENA_WINS:int 						= 472;
const ANT_ARENA_LOSSES:int 						= 473;
const ANTS_PC_BEAT_GNOLL:int 					= 474;
const ANTS_PC_LOST_TO_GNOLL:int 				= 475;
const MET_ANT_ARENA_GNOLL:int 					= 476;
const PHYLLA_CAPACITY:int 						= 873;
const ANT_KIDS:int 								= 874;
const ANT_WAIFU:int 							= 875;
const PHYLLA_STAY_HOME:int 						= 876;
const PHYLLA_CAMP_VISITS:int 					= 877;
const DAYS_PHYLLA_IN_CAMP:int 					= 878;
const PHYLLA_EGG_LAYING:int 					= 879;
const PHYLLA_BLOWJOBS:int 						= 880;
const TALKED_WITH_PHYLLA_ABOUT_HISTORY:int 		= 881;
const TIMES_LINKED_BJ_SUCK:int 					= 882;
const PHYLLA_FUCKS:int 							= 883;
const TIMES_CORRUPT_MALE_ANT_ORGY:int 			= 884;
const TIMES_CORRUPT_FEMALE_ANT_ORGY:int 		= 885;
const PHYLLA_TIMES_DRIDER_EGG_LAYED:int 		= 886;
const DAYS_PHYLLA_HAS_SPENT_BIRTHING:int 		= 887;
const ANTS_BIRTHED_FROM_LICKING:int 			= 888;
const PHYLLA_COOLDOWN:int 						= 889;
const TIMES_EGG_IMPREGNATING_PHYLLA:int 		= 890;
const PHYLLA_DRIDER_INCUBATION:int 				= 891;
const PHYLLA_DRIDER_BABIES_COUNT:int 			= 894;
const PHYLLA_INHERITED_KNOWLEDGE:int 			= 900;
const PHYLLA_IZMA_TALK:int 						= 901;
const DIDNT_FUCK_PHYLLA_ON_RECRUITMENT:int 		= 925;
const BROOKE_AFFECTION:int 						= 915;
const BROOKE_SHOWERED_WITH:int 					= 916;
const BROOKE_AND_HELIA_3SOME:int 				= 917;
const TIMES_IN_BROOKES_BUTT:int 				= 918;
const BROOKE_MEDIUM_SCENE:int 					= 919;
const BROOKE_MET:int 							= 920;
const BROOKE_MET_TODAY:int 						= 921;
const BROOKE_GRUMPS_ABOUT_TA:int 				= 922;
const SLEEP_WITH:int 							= 701;	// related to who you sleep with in camp
const ZETSUKO_MET:int 							= 406;
const CERAPH_ROLEPLAY_AS_DOMINIKA_COUNT:int 			= 389;
const CERAPH_HIDING_DICK:int 							= 288;
const TIMES_CERAPH_PORTAL_FUCKED:int 					= 438;
const TIMES_MET_CHAMELEON:int 							= 561;
const CUSTOM_PC_ENABLED:int 							= 759;
const COTTON_PREGNANCY_INCUBATION:int 					= 673;
const COTTON_PREGNANCY_TYPE:int 						= 674;
const COTTON_KID_COUNT:int 								= 675;
const COTTON_OLDEST_KID_AGE:int 						= 676;
const COTTON_OLDEST_KID_GENDER:int 						= 702;
const PC_IS_A_DEADBEAT_COTTON_DAD:int 					= 677;
const PC_IS_A_GOOD_COTTON_DAD:int 						= 678;
const COTTON_HERBS_OFF:int 								= 679;
const COTTON_CONTRACEPTION_TALK:int 					= 680;
const COTTON_KNOCKED_UP_PC_AND_TALK_HAPPENED:int 		= 681;
const VALA_CUMBATH_TIMES:int 							= 433;
const TIMES_VALA_CONSENSUAL_BIG:int 					= 767;
const TIMES_VAPULA_AND_GIANT_VALA:int 					= 768;
const HEL_AFFECTION_FOLLOWER:int 						= 478;
const HEL_FOLLOWER_LEVEL:int 							= 479;
const TOOK_GOO_ARMOR:int 								= 480;
const LOST_GOO_ARMOR_FIGHT:int 							= 481;
const WON_GOO_ARMOR_FIGHT:int 							= 482;
const HEL_REDUCED_ENCOUNTER_RATE:int 					= 483;
const MET_VALERIA:int 									= 484;
const HEL_HARPIES_DEFEATED:int 							= 485;
const HEL_DUNGEON_MEAD_LOOTED:int 						= 486;
const HEL_BRIGID_DEFEATED:int 							= 487;
const HEL_PC_TALKED_WITH_HAKON:int 						= 488;
const HEL_DUNGEON_TAKEN_WHIP:int 						= 489;
const HEL_DUNGEON_TAKEN_STRAPS:int 						= 490;
const HEL_DUNGEON_TAKEN_DAGGER:int 						= 491;
const HEL_PHOENIXES_DEFEATED:int 						= 492;
const HEL_HARPY_QUEEN_DEFEATED:int 						= 493;
const HARPY_QUEEN_EXECUTED:int 							= 494;
const HEL_KNOWS_ABOUT_HAKON:int 						= 495;
const FOUGHT_WITH_HEL_IN_DUNGEON:int 					= 496;
const TOOK_QUEEN_STAFF:int 								= 497;
const VALARIA_AT_CAMP:int 								= 498;
const SANURA_DISABLED:int 								= 833;
const MET_SANURA:int 									= 834;
const BEATEN_SANURA_COUNT:int 							= 835;
const SANDWITCH_MOB_DEFEATED:int 						= 836;
const SANDWITCH_THRONE_UNLOCKED:int 					= 837;
const SAND_WITCHES_FRIENDLY:int 						= 838;
const CUM_WITCH_DEFEATED:int 							= 839;
const ENTERED_SANDWITCH_DUNGEON:int 					= 840;
const PAWJOBS:int 										= 841;
const RIDDLE_ONE:int 									= 842;
const RIDDLE_TWO:int 									= 843;
const RIDDLE_THREE:int 									= 844;
const TIMES_SUBMITTED_TO_SANURA:int 					= 845;
const TIMES_WINFUCKED_SANURA:int 						= 846;
const SAND_MOTHER_DEFEATED:int 							= 847;
const TIMES_TENTACLED_SAND_MOTHER:int 					= 848;
const SAND_WITCHES_COWED:int 							= 849;
const SAND_WITCH_LOOT_TAKEN:int 						= 850;
const TIMES_FRIENDLY_FUCKED_SAND_MOTHER:int 			= 851;
const MORE_CUM_WITCHES:int 								= 852;
const CUM_WITCHES_FIGHTABLE:int 						= 853;
const SAND_WITCH_LEAVE_ME_ALONE:int 					= 854;
const BEEN_BLESSED_BY_CUM_WITCH:int 					= 855;
const DISCOVERED_WITCH_DUNGEON:int 						= 856;
const EDRYN_TIMES_HEL_THREESOMED:int 					= 404;
const HEL_EDRYN_OFFER:int 								= 405;
const EDRYN_PREGNANCY_INCUBATION:int 					= 68;
const TIMES_EATEN_EDRYN_PUSSY_RUT:int 					= 776;
const EMBER_AFFECTION:int 								= 523; //: Pretty obvious
const EMBER_HATCHED:int 								= 524; //: is ember hatched? 1 = true
const EMBER_GENDER:int 									= 525; // 1 for male, 2 for female, 3 for herm. This also controls the egg's shell color.
const EMBER_TYPE:int 									= 526; //numerical value: Ember is supposed to have many forms, this will control which one is born. (This is important for when Ember has hybrid forms.)
const EMBER_COR:int 									= 527; //Controls Ember's current corruption levels, only default/dragon-girl Ember uses this. (Default starting value = 50)
const EMBER_HAIR:int 									= 528; //0 for no hair, 1 for hair, 2 for mane.
const EMBER_MILK:int 									= 529; //0 for no lactation, 1 for lactating.
const EMBER_OVIPOSITION:int 							= 530; //0 for no egg laying, 1 for egg laying.
const EMBER_ROUNDFACE:int 								= 531; //0 for anthro Ember, 1 for dragon-girl Ember. (You might want to control this with the Type flag since only default Embers use this variable.)
const EMBER_EGG_FLUID_COUNT:int 						= 532; //This controls when it's time to hatch. Every item use and every time you use the egg as a masturbation aid, this will be incremented. Threshold for birthing is 5, but the birthing process can only be triggered when using as a masturbatory aid. This is done to allow players the chance to modify Ember before actually hatching.
const EMBER_STAT:int 									= 533; //All Embers have a hidden stat, Corrupt has Ego, Pure has Confidence, Tainted has Affection, and hybrids vary. There is a need to track this, but only 1 special stat for every Ember.
const EMBER_INTERNAL_DICK:int 							= 534; //Dragon-girl Ember can have either a internal sheath to keep " + emberMF("his","her") + " dick in or have it be more human-like. 0 = internal, 1 = external.
const TIMES_EQUIPPED_EMBER_SHIELD:int 					= 535;
const TOOK_EMBER_EGG:int 								= 536; //PC Take ember's egg home?
const EGG_BROKEN:int 									= 537; //PC Smash!? ember's egg?
const TIMES_FOUND_EMBERS_EGG:int 						= 538; //Times stumbled into ze egg.
const EMBER_JACKED_ON:int 								= 539; //Has the PC masturbated on the egg yet?  Needed to hatcH!
const EMBER_OVI_BITCHED_YET:int 						= 540; //Used to trigger emberBitchesAboutPCBeingFullOfEggs()
const EMBER_LUST_BITCHING_COUNTER:int 					= 541;
const EMBER_CURRENTLY_FREAKING_ABOUT_MINOCUM:int 		= 542; // Used to trigger minotaurJizzFreakout()
const DRANK_EMBER_BLOOD_TODAY:int 						= 543; //Cooldown for ember TFs
const EMBER_PUSSY_FUCK_COUNT:int 						= 544;
const TIMES_BUTTFUCKED_EMBER:int 						= 545;
const EMBER_INCUBATION:int 								= 553;
const EMBER_CHILDREN_MALES:int 							= 554;
const EMBER_CHILDREN_FEMALES:int 						= 555;
const EMBER_CHILDREN_HERMS:int 							= 556;
const EMBER_EGGS:int 									= 557;
const EMBER_BITCHES_ABOUT_PREGNANT_PC:int 				= 558;
const EMBER_TALKS_TO_PC_ABOUT_PC_MOTHERING_DRAGONS:int 	= 559;
const EMBER_PREGNANT_TALK:int 							= 560;
const TIMES_EMBER_LUSTY_FUCKED:int 						= 824;
const JOEY_OFFERED_MILKER:int 							= 466;
const OWN_MAIDEN_BIKINI:int 							= 770;
const COUNTDOWN_TO_NIGHT_RAPE:int 						= 872;
const SOCK_COUNTER:int 									= 895;
const SOCK_HOLDING:int 									= 896;
const FOUND_SOCKS:int 									= 897;
const SOCKS_BOUGHT:int 									= 898;
const MIDAS_JERKED:int 									= 899;
const LAST_EASTER_YEAR:int 								= 823;
const ARIAN_FOLLOWER:int 								= 933;
const ARIAN_PARK:int 									= 934; //-1 = disabled, 1 = helped.
const ARIAN_HEALTH:int 									= 935; //Higher is better.
const ARIAN_ANAL_XP:int 								= 936;
const ARIAN_CAPACITY:int 								= 937;
const ARIAN_COCK_SIZE:int 								= 938;
const ARIAN_DOUBLE_COCK:int 							= 939;
const ARIAN_VAGINA:int 									= 940;
const ARIAN_BREASTS:int 								= 941;
const ARIAN_VIRGIN:int 									= 942;
const ARIAN_S_DIALOGUE:int 								= 943;
const ARIAN_HERM_CHAT:int 								= 944;
const ARIAN_ASS_CHAT:int 								= 945;
const ARIAN_LESSONS:int 								= 946;
const ARIAN_DOUBLE_PENETRATION_CHAT:int 				= 947;
const ARIAN_FIRST_REPTILUM:int 							= 948;
const ARIAN_TREATMENT:int 								= 949;
const ARIAN_EGG_CHAT:int 								= 952;
const ARIAN_EGG_EVENT:int 								= 953;
const ARIAN_EGG_COLOR:int 								= 954;
const ARIAN_EGG_COUNTER:int 							= 955;
const ARIAN_HAS_BLOWN:int 								= 950;
const ARIAN_MORNING:int 								= 951;
const TIMES_ARIAN_DILDOED:int 							= 983;
const AMILY_TREE_FLIPOUT:int 							= 599;
const AMILY_X_JOJO_COOLDOWN:int 							= 435;
const ASKED_IZMA_ABOUT_WANG_REMOVAL:int 							= 440;
const BIKINI_ARMOR_BONUS:int 							= 769;
const BOG_EXPLORED:int 							= 1016;
const BOOBGARTUAN_SURPRISE_COUNT:int 							= 414;
const BROKE_UP_WITH_MARBLE:int 							= 459;
const CAME_WORMS_AFTER_COMBAT:int 							= 788;
const CANDY_CANE_YEAR_MET:int 							= 637;
const DAUGHTER_FOUR_BIMBO:int 							= 753;
const DAUGHTER_ONE_BIMBO:int 							= 750;
const DAUGHTER_THREE_BIMBO:int 							= 752;
const DAUGHTER_TWO_BIMBO:int 							= 751;
const DAYS_SINCE_LAST_DEMON_DEALINGS:int 							= 505;
const DECLINED_TO_VISIT_REBECCS_VILLAGE:int 							= 500;
const DICK_EGG_INCUBATION:int 							= 592;
const DISCUSSED_LUBE_SPRAY:int 							= 811;
const DISCUSSED_URTA_ALCOHOLISM:int 							= 445;
const DOMINIKA_LAST_HYPNO_SUCK_COUNT:int 							= 388;
const DOMINIKA_TIMES_HYPNO_BJ:int 							= 387;
const DOMINIKA_TIMES_MULTICOCK_SLOBBERED:int 							= 386;
const DOMINIKAS_SWORD_GIVEN:int 							= 416;
const DOUBLE_ATTACK_STYLE:int 							= 867;
const EDRYN_BIRF_COUNTDOWN:int 							= 722;
const EGG_WITCH_COUNTER:int 							= 588;
const EGG_WITCH_TYPE:int 							= 589;
const EGGS_BOUGHT:int 							= 653;
const ESSRAYLE_ESCAPED_DUNGEON:int 							= 863;
const ESSY_DUNGEON_FUCKED:int 							= 865;
const ESSY_MET_IN_DUNGEON:int 							= 866;
const EVENT_PARSER_ESCAPE:int 							= 800;
const EVER_INFESTED:int 							= 787;
const EXGARTUAN_TIGHTPANTS_MASTURBATE_COUNT:int 							= 413;
const EXPLORATION_PAGE:int 							= 1015;
const FARM_DISABLED:int 							= 464;
const FED_SCYLLA_TODAY:int 							= 779;
const FIRST_TIME_AT_URTA_HOUSE:int 							= 809;
const FOLLOWER_HEL_TALKS:int 							= 670;
const FOUGHT_HOLLI:int 							= 923;
const FOUND_ISABELLA_AT_FARM_TODAY:int 							= 707;
const FOX_BAD_END_WARNING:int 							= 477;
const FUCK_FLOWER_GROWTH_COUNTER:int 							= 597;
const FUCK_FLOWER_KILLED:int 							= 598;
const FUCK_FLOWER_LEVEL:int 							= 596;
const GAR_CATHEDRAL:int 							= 830;
const GAR_CONFIDENCE:int 							= 826;
const GAR_HISTORY:int 							= 829;
const GAR_NAME:int 							= 825;
const GAR_NAME_TALKS:int 							= 831;
const GATS_ANGEL_DISABLED:int 							= 639;
const GATS_ANGEL_GOOD_ENDED:int 							= 638;
const GATS_ANGEL_QUEST_BEGAN:int 							= 640;
const GATS_ANGEL_TIME_TO_FIND_KEY:int 							= 641;
const GENDERLESS_MASTURBATION_WITH_GHOST_COUNT:int 							= 511;
const GHOST_GIRL_SLIME_X_SHOULDRA_COUNTER:int 							= 510;
const GOO_DICK_LENGTH:int 							= 667;
const GOO_DICK_TYPE:int 							= 668;
const GOO_EYES:int 							= 658;
const GOO_FLUID_AMOUNT:int 							= 664;
const GOO_HAPPINESS:int 							= 662;
const GOO_INDIRECT_FED:int 							= 670;
const GOO_NAME:int 							= 656;
const GOO_NIPPLE_TYPE:int 							= 666;
const GOO_OBEDIENCE:int 							= 663;
const GOO_PREFERRED_TIT_SIZE:int 							= 665;
const GOO_SLAVE_RECRUITED:int 							= 657;
const GOO_TFED_MEAN:int 							= 654;
const GOO_TFED_NICE:int 							= 655;
const GOO_TOSSED_AFTER_NAMING:int 							= 659;
const GOOGIRL_BIRTHS:int 							= 384;
const GOOGIRL_CONSECUTIVE_LOSSES:int 							= 385;
const GOT_NIAMH_BEER:int 							= 447;
const GOTTEN_INQUISITOR_ARMOR:int 							= 415;
const HAD_FIRST_HELSPAWN_TALK:int 							= 969;
const HAKON_AND_KIRI_VISIT:int 							= 975;
const HAS_SEEN_MINO_AND_COWGIRL:int 							= 892;
const HEL_AFFECTION:int 							= 395;
const HEL_BONUS_POINTS:int 							= 966;
const HEL_CAN_SWIM:int 							= 703;
const HEL_FOXY_FOURSOME_WARNED:int 							= 417;
const HEL_FUCK_COUNTER:int 							= 394;
const HEL_FUCKBUDDY:int 							= 393;
const HEL_GUARDING:int 							= 704;
const HEL_INTROS_LEVEL:int 							= 697;
const HEL_ISABELLA_THREESOME_ENABLED:int 							= 397;
const HEL_LOVE:int 							= 962;
const HEL_NTR_TRACKER:int 							= 965;
const HEL_PREGNANCY_INCUBATION:int 							= 967;
const HEL_PREGNANCY_NOTICES:int 							= 968;
const HEL_RAPED_TODAY:int 							= 706;
const HEL_TALK_EIGHT:int 							= 971;
const HEL_TALKED_ABOUT_ATTACKING_YOU:int 							= 392;
const HEL_TALKED_ABOUT_BERSERKING:int 							= 390;
const HEL_TALKED_ABOUT_HER:int 							= 391;
const HEL_TIMES_ENCOUNTERED:int 							= 396;
const HELIA_ANAL_TRAINING:int 							= 927;
const HELIA_ANAL_TRAINING_OFFERED:int 							= 926;
const HELIA_BDAY_DRINKS:int 							= 929;
const HELIA_BDAY_FOX_TWINS:int 							= 932;
const HELIA_BDAY_HAKON_AND_KIRI:int 							= 930;
const HELIA_BDAY_PHOENIXES:int 							= 931;
const HELIA_BIRTHDAY_OFFERED:int 							= 928;
const HELIA_FOLLOWER_DISABLED:int 							= 696;
const HELIA_KIDS_CHAT:int 							= 963;
const HELIA_TALK_SEVEN:int 							= 964;
const HELSPAWN_AGE:int 							= 960;
const HELSPAWN_DADDY:int 							= 958;
const HELSPAWN_DISCOVER_BOOZE:int 							= 972;
const HELSPAWN_FUCK_INTERRUPTUS:int 							= 973;
const HELSPAWN_GROWUP_COUNTER:int 							= 961;
const HELSPAWN_INCEST:int 							= 970;
const HELSPAWN_NAME:int 							= 956;
const HELSPAWN_PERSONALITY:int 							= 957;
const HELSPAWN_WEAPON:int 							= 959;
const HOLLI_DEFENSE_ON:int 							= 602;
const HOLLI_FRUIT:int 							= 600;
const HOLLI_FRUIT_EXPLAINED:int 							= 601;
const HOLLI_SUBMISSIVE:int 							= 682;
const ISABELLA_ACCENT_FORCED_ON:int 							= 374;
const ISABELLA_ACCENT_TRAINING_COOLDOWN:int 							= 373;
const ISABELLA_ACCENT_TRAINING_PERCENT:int 							= 372;
const ISABELLA_AFFECTION:int 							= 368;
const ISABELLA_BLOWJOBS_DISABLED:int 							= 376;
const ISABELLA_CAMP_DISABLED:int 							= 371;
const ISABELLA_FOLLOWER_ACCEPTED:int 							= 369;
const ISABELLA_MILK_COOLDOWN:int 							= 380;
const ISABELLA_MILKED_YET:int 							= 375;
const ISABELLA_MORNING_FELLATIO_COUNT:int 							= 377;
const ISABELLA_MURBLE_BLEH:int 							= 381;
const ISABELLA_PLAINS_DISABLED:int 							= 370;
const ISABELLA_PROBOVA_BURP_COUNT:int 							= 383;
const ISABELLA_SPARRING_INTRO:int 							= 382;
const ISABELLA_TIME_SINCE_LAST_HOTDOGGING:int 							= 378;
const ISABELLA_TIMES_HOTDOGGED:int 							= 379;
const ISABELLA_TIMES_OFFERED_FOLLOWER:int 							= 367;
const IZMA_NO_COCK:int 							= 439;
const IZMA_X_LATEXY_DISABLED:int 							= 784;
const JACK_FROST_PROGRESS:int 							= 646;
const JACK_FROST_YEAR:int 							= 645;
const JOJO_EGGCUBATE_COUNT:int 							= 591;
const JOJO_MOVE_IN_DISABLED:int 							= 550;
const KAIJU_BAD_END_COUNTER:int 							= 914;
const KAIJU_COCK:int 							= 913;
const KAIJU_DISABLED:int 							= 911;
const KAIJU_MEETINGS:int 							= 910;
const KAIJU_TALK_CYCLE:int 							= 912;
const KAMI_ENCOUNTER:int 							= 643;
const KATHERINE_BALL_SIZE:int 							= 402;
const KATHERINE_DICK_COUNT:int 							= 399;
const KATHERINE_DICK_LENGTH:int 							= 400;
const KATHERINE_KNOT_THICKNESS:int 							= 401;
const KATHERINE_TIMES_SEXED:int 							= 403;
const KATHERINE_UNLOCKED:int 							= 398;
const KEEP_HELIA_AND_SOPHIE:int 							= 699;
const KELLY_BONUS_BOOB_ROWS:int 							= 904;
const KELLY_BONUS_TIT_ROWS:int 							= 732;
const KELLY_CUNT_TYPE:int 							= 726;
const KELLY_DISOBEYING_COUNTER:int 							= 734;
const KELLY_FIRST_KID_GENDER:int 							= 909;
const KELLY_HAIR_COLOR:int 							= 976;
const KELLY_HEAT_TIME:int 							= 907;
const KELLY_INCUBATION:int 							= 905;
const KELLY_KIDS:int 							= 908;
const KELLY_LACTATING:int 							= 733;
const KELLY_REWARD_COOLDOWN:int 							= 981;
const KELLY_TALK_N_HAND_TIMES:int 							= 977;
const KELLY_TIMES_APPLESAUCED:int 							= 980;
const KELLY_TIMES_DIED_HAIR:int 							= 979;
const KELLY_TIMES_PEPPERED:int 							= 906;
const KELLY_TIMES_REWARDED:int 							= 978;
const KELLY_VAGINALLY_FUCKED_COUNT:int 							= 735;
const KELT_BREAK_LEVEL:int 							= 725;
const KIHA_ADMITTED_WARM_FEELINZ:int 							= 426;
const KIHA_AFFECTION:int 							= 422;
const KIHA_AFFECTION_LEVEL:int 							= 421;
const KIHA_AND_HEL_WHOOPIE:int 							= 425;
const KIHA_CAMP_WATCH:int 							= 982;
const KIHA_CERVIXGINITY_TAKEN:int 							= 430;
const KIHA_CHOKED_OUT_PC:int 							= 432;
const KIHA_CORRUPTION_BITCH:int 							= 423;
const KIHA_FOLLOWER:int 							= 428;
const KIHA_HORSECOCK_FUCKED:int 							= 431;
const KIHA_MOVE_IN_OFFER:int 							= 427;
const KIHA_NEED_SPIDER_TEXT:int 							= 424;
const KIHA_NEEDS_TO_REACT_TO_HORSECOCKING:int 							= 429;
const KIHA_TALK_STAGE:int 							= 344;
const KIHA_TOLL:int 							= 341;
const KIHA_TOLL_DURATION:int 							= 342;
const KINKY_RITUALS_SPOKEN:int 							= 828;
const KITSUNE_SHRINE_VISIT:int 							= 708;
const LATEX_GOO_TIMES_FEMDOMMED_BY_PC:int 							= 672;
const LIANNA_HAVESTED_LADIES:int 							= 808;
const LIANNA_HAVESTED_MALES:int 							= 807;
const LOPPE_DENIAL_COUNTER:int 							= 692;
const LOPPE_DISABLED:int 							= 693;
const LOPPE_FERTILE:int 							= 685;
const LOPPE_FURRY:int 							= 684;
const LOPPE_KIDS:int 							= 686;
const LOPPE_KIDS_LIMIT:int 							= 688;
const LOPPE_MET:int 							= 695;
const LOPPE_PC_MET_UMA:int 							= 690;
const LOPPE_TIMES_SEXED:int 							= 691;
const LOPPE_TRAINING:int 							= 687;
const LOPPE_URTA_CHATS:int 							= 689;
const MALI_TAKEN_BLADE:int 							= 862;
const MANSION_VISITED:int 							= 626;
const MARBLE_BOVA_LEVEL:int 							= 465;
const MARBLE_CAMPTALK_LEVEL:int 							= 461;
const MARBLE_KIDS:int 							= 8;
const MARBLE_LUST:int 							= 3;
const MARBLE_PLAYED_WITH_KIDS_TODAY:int 							= 460;
const MARBLE_TELADRE_STORY:int 							= 462;
const MARBLE_WARNING:int 							= 463;
const MET_ESSY:int 							= 772;
const MET_KITSUNES:int 							= 628;
const MET_MILK_SLAVE:int 							= 871;
const MET_MINERVA:int 							= 821;
const MET_NIAMH:int 							= 446;
const MET_OLIVIA:int 							= 822;
const MET_OTTERGIRL:int 							= 777;
const MILK_NAME:int 							= 869;
const MILK_SIZE:int 							= 870;
const MINERVA_BACKSTORY:int 							= 814;
const MINERVA_BACKSTORY_LEARNED:int 							= 815;
const MINERVA_LEZZES_OUT:int 							= 820;
const MINERVA_LOVE:int 							= 813;
const MINO_SONS_HAVE_SOPHIE:int 							= 698;
const MURBLE_FARM_TALK_LEVELS:int 							= 458;
const NEED_URTA_LETTER:int 							= 799;
const NEVER_RESIST_KELT:int 							= 727;
const NEW_BABY_ANNOUNCED:int 							= 810;
const NIAMH_MOVED_OUT_COUNTER:int 							= 449;
const NIAMH_SEAN_BREW_BIMBO_LIQUEUR_COUNTER:int 							= 451;
const NIAMH_STATUS:int 							= 450;
const NIEVE_GENDER:int 							= 648;
const NIEVE_MOUTH:int 							= 649;
const NIEVE_STAGE:int 							= 647;
const NO_PURE_SOPHIE_RECRUITMENT:int 							= 754;
const OWCA_ANGER_DISABLED:int 							= 508;
const OWCA_SACRIFICE_DISABLED:int 							= 548;
const OWCA_UNLOCKED:int 							= 506;
const OWCAS_ATTITUDE:int 							= 503;
const PC_DISLIKES_URTA_AND_EDRYN_TOGETHER:int 							= 444;
const PC_KNOWS_ABOUT_BLACK_EGGS:int 							= 661;
const PC_PROMISED_HEL_MONOGAMY_FUCKS:int 							= 705;
const PC_WIN_LAST_KIHA_FIGHT:int 							= 345;
const PHYLLA_GEMS_HUNTED_TODAY:int 							= 893;
const POLAR_PETE_YEAR_MET:int 							= 644;
const PUMPKIN_FUCK_YEAR_DONE:int 							= 522;
const RATHAZUL_DEBIMBO_OFFERED:int 							= 744;
const REBECCS_LAST_PLEA:int 							= 507;
const redheadIsFuta:int 							= 627;
const RITUAL_INTRO:int 							= 827;
const ROGAR_DIRT:int 							= 408;
const ROGAR_DISABLED:int 							= 410;
const ROGAR_FUCKED_TODAY:int 							= 411;
const ROGAR_PHASE:int 							= 407;
const ROGAR_WARNING:int 							= 409;
const RUBI_ADMITTED_GENDER:int 							= 606;
const RUBI_AFFECTION:int 							= 604;
const RUBI_BALLS_TYPE:int 							= 997;
const RUBI_BAR_CONFESSION:int 							= 1009;
const RUBI_BIMBO:int 							= 610;
const RUBI_BIMBO_MINIDRESS:int 							= 625;
const RUBI_BLU_BALLS:int 							= 608;
const RUBI_BODYSUIT:int 							= 616;
const RUBI_BONDAGE_STRAPS:int 							= 1012;
const RUBI_BREAST_SIZE:int 							= 984;
const RUBI_COCK_SIZE:int 							= 985;
const RUBI_COCK_TYPE:int 							= 986;
const RUBI_CUNTTYPE:int 							= 991;
const RUBI_DEBIMBO:int 							= 1002;
const RUBI_DISABLED:int 							= 605;
const RUBI_EAR_TYPE:int 							= 998;
const RUBI_EYE_DESCRIPT:int 							= 992;
const RUBI_EYE_TYPE:int 							= 993;
const RUBI_FANCY_CONFESSION:int 							= 1008;
const RUBI_FEET:int 							= 1001;
const RUBI_FETISH_CLOTHES:int 							= 613;
const RUBI_GOT_BIMBO_SKIRT:int 							= 623;
const RUBI_GREEN_ADVENTURER:int 							= 614;
const RUBI_HAIR:int 							= 995;
const RUBI_HAIR_LENGTH:int 							= 996;
const RUBI_HANDS:int 							= 999;
const RUBI_HORNTYPE:int 							= 988;
const RUBI_ICECREAM_CONFESSION:int 							= 1006;
const RUBI_INCUBUS_PROGRESS:int 							= 611;
const RUBI_INQUISITORS_CORSET:int 							= 1013;
const RUBI_INTRODUCED:int 							= 607;
const RUBI_LONGDRESS:int 							= 617;
const RUBI_LOWERBODY:int 							= 987;
const RUBI_NIPPLE_TYPE:int 							= 1003;
const RUBI_NIPPLETYPE:int 							= 989;
const RUBI_NO_CUNT:int 							= 990;
const RUBI_NURSE_CLOTHES:int 							= 619;
const RUBI_ORGASM_DENIAL:int 							= 609;
const RUBI_PROFIT:int 							= 624;
const RUBI_PROSTITUTION:int 							= 621;
const RUBI_SETUP:int 							= 1014;
const RUBI_SHE:int 							= 1004;
const RUBI_SKIN:int 							= 994;
const RUBI_SUITCLOTHES:int 							= 612;
const RUBI_SWIMWEAR:int 							= 620;
const RUBI_TIGHT_PANTS:int 							= 618;
const RUBI_TIMES_ANALLY_TRAINED:int 							= 1010;
const RUBI_TIMES_GIVEN_AN_ITEM:int 							= 1011;
const RUBI_TUBE_TOP:int 							= 615;
const RUBI_WHISKERS:int 							= 1000;
const RUBIS_HOUSE_FIRST_TIME:int 							= 622;
const SALON_PAID:int 							= 441;
const SANDTRAP_LOSS_REPEATS:int 							= 812;
const SANDTRAP_NAGA_3SOME:int 							= 579;
const SATYR_KIDS:int 							= 603;
const SHEILA_CITE:int 							= 765;
const SHEILA_CLOCK:int 							= 858;
const SHEILA_CORRUPTION:int 							= 760;
const SHEILA_DEMON:int 							= 764;
const SHEILA_IMPS:int 							= 859;
const SHEILA_JOEYS:int 							= 763;
const SHEILA_XP:int 							= 761;
const SHOULDRA_BAKERY_TIMES:int 							= 521;
const SHOULDRA_EXGARTUAN_SPIRIT_SEX_COUNT:int 							= 360;
const SHOULDRA_EXGARTUDRAMA:int 							= 520;
const SHOULDRA_FOLLOWER_STATE:int 							= 513;
const SHOULDRA_GENDERLESS_FUCK_COUNT:int 							= 357;
const SHOULDRA_HERMSEX_COUNT:int 							= 362;
const SHOULDRA_MAGIC_COOLDOWN:int 							= 518;
const SHOULDRA_MET_VALA:int 							= 766;
const SHOULDRA_PENIS_DEFEAT_TIMES:int 							= 358;
const SHOULDRA_PLOT_COUNTDOWN:int 							= 516;
const SHOULDRA_PLOT_LEVEL:int 							= 514;
const SHOULDRA_SLEEP_TIMER:int 							= 517;
const SHOULDRA_SLIME_PENOR_TIMES:int 							= 356;
const SHOULDRA_TALK_NEEDED:int 							= 515;
const SHOULDRA_TIMES_NIGHT_RAPED_PC:int 							= 519;
const SHOULDRA_TONGUE_LICKS_TIMES:int 							= 512;
const SHOULDRA_USES_YOUR_GIANT_COCK_COUNT:int 							= 363;
const SHOULDRA_VAGINAL_POSSESSIONS:int 							= 361;
const SHOULDRA_WORM_SCENE_COUNTER:int 							= 359;
const SLIMEGINAED:int 							= 509;
const SOPHIE_ADULT_KID_COUNT:int 							= 740;
const SOPHIE_BROACHED_SLEEP_WITH:int 							= 739;
const SOPHIE_DAUGHTER_MATURITY_COUNTER:int 							= 741;
const SOPHIE_DEBIMBOED:int 							= 745;
const SOPHIE_EGG_COUNTER:int 							= 742;
const SOPHIE_FAMILY_INCEST:int 							= 743;
const SOPHIE_FOLLOWER_IRRITATION:int 							= 748;
const SOPHIE_FOLLOWER_PROGRESS:int 							= 755;
const SOPHIE_HEAT_COUNTER:int 							= 737;
const SOPHIE_INCUBATION:int 							= 738;
const SOPHIE_RECRUITED_PURE:int 							= 747;
const SOPHIES_DAUGHTERS_DEBIMBOED:int 							= 746;
const SPELLS_CAST:int 							= 868;
const SPIDER_BRO_GIFT:int 							= 974;
const SUCCUBI_MILKED_GNOLL_PRINCESS:int 							= 713;
const TALKED_NIAMH:int 							= 448;
const TAMANI_TIME_OUT:int 							= 580;
const THREATENED_HOLLI:int 							= 924;
const TIMED_SHARKGINAS:int 							= 354;
const TIMES_AMILY_AND_JOJO_PLAYED_TIMES:int 							= 434;
const TIMES_ASKED_LOPPE_ABOUT_LOPPE:int 							= 694;
const TIMES_BEATEN_SHOULDRA:int 							= 352;
const TIMES_BEEN_TO_LIBRARY:int 							= 861;
const TIMES_BUTTFUCKED_MINERVA:int 							= 817;
const TIMES_DISCUSSED_RUBIS_IDENTITY:int 							= 1005;
const TIMES_DOMMED_HECKEL:int 							= 651;
const TIMES_EGGED_IN_COCK:int 							= 593;
const TIMES_EGGED_JOJO:int 							= 590;
const TIMES_ENCOUNTERED_FROG:int 							= 1017;
const TIMES_ENCOUNTERED_SAND_TRAPS:int 							= 578;
const TIMES_FED_LATEXY_MINO_CUM:int 							= 671;
const TIMES_FUCKED_FLOWER:int 							= 594;
const TIMES_FUCKED_NORMAL_GOOS:int 							= 660;
const TIMES_HELIA_DOUBLE_DONGED:int 							= 786;
const TIMES_IN_DEMON_PIT:int 							= 501;
const TIMES_IZMA_DOMMED_LATEXY:int 							= 785;
const TIMES_LOST_HECKEL_DOM_CHALLENGE:int 							= 650;
const TIMES_MASSAGED_URTA_BELLY:int 							= 803;
const TIMES_MET_CHICKEN_HARPY:int 							= 652;
const TIMES_MET_KIHA:int 							= 343;
const TIMES_MET_OOZE:int 							= 364;
const TIMES_MET_SHOULDRA:int 							= 351;
const TIMES_MINERVA_COWGIRLED:int 							= 818;
const TIMES_MINERVA_LAPSEXED:int 							= 819;
const TIMES_MINERVA_SEXED:int 							= 816;
const TIMES_MORNING_SOPHIE_FEMDOMMED:int 							= 749;
const TIMES_NIAMH_BAZAAR_MET:int 							= 452;
const TIMES_NURSED_FROM_URTA:int 							= 805;
const TIMES_ORPHANAGED_WITH_RAPHAEL:int 							= 683;
const TIMES_OVIPOSITED_TAMANI:int 							= 581;
const TIMES_POSSESSED_BY_SHOULDRA:int 							= 353;
const TIMES_PUNISHED_KELLY:int 							= 729;
const TIMES_REFUSED_REBECCS_OFFER:int 							= 502;
const TIMES_RIDDEN_FLOWER:int 							= 595;
const TIMES_RIDDEN_KELLY_FOR_PUNISHMENT:int 							= 731;
const TIMES_RIM_JOBBED_BY_KELLY:int 							= 730;
const TIMES_RUBI_DATED:int 							= 1007;
const TIMES_RUBI_MASSAGED:int 							= 832;
const TIMES_SHARKPENISED:int 							= 355;
const TIMES_SOLO_FED_NUN:int 							= 778;
const TIMES_SOPHIE_AND_IZMA_FUCKED:int 							= 780;
const TIMES_THOUGHT_ABOUT_GOO_RECRUITMENT:int 							= 669;
const TIMES_URTA_BOOB_WORSHIPPED:int 							= 804;
const TIMES_VISITED_MALI:int 							= 860;
const TOLD_MOTHER_TO_RELEASE_ESSY:int 							= 864;
const TOLD_SOPHIE_TO_IZMA:int 							= 781;
const TOOK_KITSUNE_STATUE:int 							= 709;
const TURKEY_FUCK_YEAR_DONE:int 							= 566;
const TURNED_DOWN_ESSY_FIRST_MEETING:int 							= 773;
const URTA_BECOMES_SNAKE_SLAVE:int 							= 715;
const URTA_CUM_NO_CUM_DAYS:int 							= 782;
const URTA_EGG_FORCE_EVENT:int 							= 584;
const URTA_EGG_INCUBATION:int 							= 586;
const URTA_EGGS:int 							= 582;
const URTA_FAMILY_TALK_ATTEMPTS:int 							= 442;
const URTA_FERTILE:int 							= 723;
const URTA_FERTILE_EGGS:int 							= 583;
const URTA_FIRSTBORN_COCKTYPE:int 							= 796;
const URTA_FIRSTBORN_GENDER:int 							= 795;
const URTA_FLATBELLY_NOTICE:int 							= 587;
const URTA_FUCKED_HEL:int 							= 712;
const URTA_GOBLIN_SLAVE:int 							= 716;
const URTA_INCUBATION:int 							= 789;
const URTA_INCUBATION_CELEBRATION:int 							= 801;
const URTA_IS_VULQUINE_MENACE:int 							= 719;
const URTA_KIDS_FEMALES:int 							= 793;
const URTA_KIDS_HERMS:int 							= 794;
const URTA_KIDS_MALES:int 							= 792;
const URTA_LATESTBORN_COCKTYPE:int 							= 798;
const URTA_LATESTBORN_GENDER:int 							= 797;
const URTA_LUNCH_PLAY:int 							= 806;
const URTA_MET_HEL:int 							= 710;
const URTA_MINO_AND_SUCCUBI_SLAVE:int 							= 721;
const URTA_OPEN_ABOUT_EDRYN:int 							= 443;
const URTA_PETPLAY_DONE:int 							= 857;
const URTA_PREG_EVERYBODY:int 							= 724;
const URTA_PREGNANT_DELIVERY_SCENE:int 							= 802;
const URTA_QUEST_STATUS:int 							= 711;
const URTA_RAPED_MINO_LORD:int 							= 720;
const URTA_SCYLLA_BIG_DICK_TIMES_DONE:int 							= 633;
const URTA_TAKEN_BY_GNOLLS:int 							= 714;
const URTA_TENTACLE_GAPED:int 							= 718;
const URTA_TENTACLE_RAPED:int 							= 717;
const URTA_TIMES_BIRTHED:int 							= 790;
const URTA_TIMES_EGG_PREGGED:int 							= 585;
const URTA_TIMES_PC_BIRTHED:int 							= 791;
const URTA_X_RAPHAEL_HAPPENED:int 							= 783;
const VALENTINES_EVENT_YEAR:int 							= 736;
const VAPULA_DAYS_SINCE_FED:int 							= 551;
const VAPULA_EARNED_A_SPANK:int 							= 634;
const VAPULA_FOLLOWER:int 							= 549;
const VAPULA_HAREM_FUCK:int 							= 546;
const VAPULA_SUBMISSIVENESS:int 							= 504;
const VAPULA_TEASE_COUNT:int 							= 552;
const VAPULA_THREESOMES:int 							= 547;
const VELARIA_FUTA:int 							= 499;
const WHITNEY_FLIPPED_OUT_OVER_KELLY:int 							= 728;
const XMAS_CHICKEN_YEAR:int 							= 642;
const YVONNE_FUCK_COUNTER:int 							= 437;
const ACCEPTED_ESSY_FIRST_MEETING:int = 774;
const SHEILA_PREG:int = 762;
const TIMES_USED_SEX_MACHINE_AS_MALE:int                                   =  183; // Times Used Sex Machine As Male
const TIMES_USED_SEX_MACHINE_AS_FEMALE:int                                   =  184; // Times Used Sex Machine As Female
const TIMES_USED_SEX_MACHINE_AS_EUNUCH:int                                   =  185; // Times Used Sex Machine As Genderless
const TIMES_USED_SEX_MACHINE_AS_HERM:int                                   =  186; // Times Used Sex Machine As Herm
const NEW_GAME_PLUS_BONUS_STORED_XP:int                                   =  187; // New Game Plus - Stored XP
const NEW_GAME_PLUS_BONUS_STORED_ITEMS:int                                   =  188; // New Game Plus - Stored Gems
const NEW_GAME_PLUS_BONUS_WEAPON_NAME:int                                   =  189; // NG+ Weapon name
const NEW_GAME_PLUS_BONUS_WEAPON_VALUE:int                                   =  190; // NG+ Weapon Value
const NEW_GAME_PLUS_BONUS_WEAPON_PERK:int                                   =  191; // NG+ Weapon Perk
const NEW_GAME_PLUS_BONUS_WEAPON_VERB:int                                   =  192; // NG+ Weapon Verb
const NEW_GAME_PLUS_BONUS_WEAPON_ATTACK:int                                   =  193; // NG+ Weapon Attack
const NEW_GAME_PLUS_BONUS_ARMOR_NAME:int                                   =  194; // NG+ Armor Name
const NEW_GAME_PLUS_BONUS_ARMOR_PERK:int                                   =  195; // NG+ Armor Perk
const NEW_GAME_PLUS_BONUS_ARMOR_DEFENSE:int                                   =  196; // NG+ ArmorDef
const NEW_GAME_PLUS_BONUS_ARMOR_VALUE:int                                   =  197; // NG + Armor Value
const TEMP_STORAGE_PASTRY_NAME:int                                   =  198; // Holding pattern for pastry name
const TEMP_STORAGE_PASTRY_PRICE:int                                   =  199; // Holding pattern for price
const MINOTAUR_CUM_ECLAIR_UNLOCKED:int                                   =  200; // Unlocked mino cum eclair
const TIMES_VISITED_BAKERY:int                                   =  201; // Times visited bakery
const TIMES_FUCKED_HECKEL_BLOWJOB:int                                   =  202; // Times Heckel BJ
const TIMES_FUCKED_HECKEL_ANAL:int                                   =  203; // Times Heckel Anal
const MET_HECKEL:int                                   =  204; // Met Heckel
const MET_IFRIS:int                                   =  205; // Met Ifris
const TIMES_FUCKED_IFRIS_BLOWJOB:int                                   =  206; // Ifris sucked?
const TIMES_FUCKED_IFRIS_LICKED:int                                   =  207; // Ifris licked?
const IFRIS_SHOWED_OFF:int                                   =  208; // Shown off for ifris
const HAVE_ENCOUNTERED_GNOLL_PLAINS:int                                   =  209; // New gnoll met?
const BAZAAR_SLIPPERY_SQUEEZE_VISITED:int                                   =  210; // Visited the Slippery Squeeze?
const BAZAAR_ENTERED:int                                   =  211; // Entered the bizarre bazaar?
const BAZAAR_ENCOUNTERED:int                                   =  212; // Found the bazaar previously?
const CINNABAR_HOUSE_VISITED:int                                   =  213; // -Been to Cinnabar's House?


const CINNABAR_NUMBER_ENCOUNTERS:int                                   =  214; // -CINNABAR Introduced?
const CINNABAR_NUMBER_TIMES_FUCKED:int                                   =  215; // -CINNABAR Times Fucked
const CINNABAR_FUCKED_CORRUPT_PREVIOUSLY:int                                   =  216; // -CINNABARWas last fuck corrupt fuck? - Cinnabar Hard Fucked.	0=No, 1=Yes