//NOT FINISHED
package classes.Scenes.NPCs 
{
	import classes.*;
	import classes.GlobalFlags.*;
	
	/**
	 * Izmael by Nonesuch
	 * @author Kitteh6660
	 */
	public class IzmaelScene extends NPCAwareContent
	{
		
		public function IzmaelScene() 
		{
			
		}
		
		public function brotizeIzma():void {
			clearOutput();
			outputText("You call Izma and take a moment to consider your tiger shark beta as she sashays over to you.  Although it is always a pleasure to take in her toned, well-nigh perfect body, the more you look at her the more you come to realize that there’s something which imperceptibly but endlessly annoys you about her.  Perhaps it’s in the way she smirks ever so slightly when you call her over.  Or the way she moves around the camp with such swaggering confidence, as if she were the one who really owns it, and you’re just filling in for her.  Or the way she has that chest of hers within reach at all times, as if either you or one of your other followers could try and steal it at any time.  Or her dick.  Even now as she approaches you, she swings her hips faintly to make her formidable member swing beneath her skirt, hoping you’ll notice it perhaps or reassuring herself with its heavy movement.  It’s so damn important to her, that dick; her entire damn world seems to revolve around it.  You suppose you can’t blame her.  Beneath her flimsy attempts at intellect she is hardwired to be an alpha animal, to stick it into as many holes as she can, to fuck, sire and forget.  This whole beta thing you’ve got going on is just a game to her, you see that clearly now; it doesn’t matter how many times you assert your dominance, in her head she’s still the daddy and you’re the little girl.  You realise you’re building yourself into a needless rage with this train of thought, that you’re probably being unfair, and yet you don’t stop yourself- with the righteous anger, you feel, comes an ability to think clearer.  To plot.");
			outputText("\n\n“<i>Alpha?</i>” Izma is looking at you, amusement overlaying anxiety on her pretty, pointed face.  “<i>Is everything alright?</i>” You assure her everything’s fine, and ask if she’s caught any fish in the stream today; you’d like to sit down and share a meal with her.  “<i>Oh, what a nice idea! I‘ve got two hung on the frame from the morning swarm.  Uh… you prefer stuff cooked, don’t you?</i>” You sit down and watch her trot back towards the stream, tail swaying.  You want to take her down several notches, quash forever the niggling suspicion she’s fucking around with you.  You suppose you could take away her cock, make her more sensitive...[Izma dedicked in past: you sigh, remembering the hullabaloo that caused last time.] No, it’s not good enough.  Doing that would merely validate her worldview that the ones with the biggest dicks are the ones naturally in control.  If only you could damn her somehow with that all-important phallus of hers.  How ironic that would be… it is then that something rounded and metal in one of your pockets digs into your side, as if it had been sat there waiting for this moment all along.  A smile spreads over your face as the deliciously wicked idea forms.");
			outputText("\n\nIzma soon returns, her catch proudly slung over one shoulder, and with the natural skill of someone who has lived next to a lake all her life soon has the fish gutted, scaled and roasting over a fire.  You eat the tender white flesh carefully, watching the shark herm devour her share messily.  Casually, you ask if she fancies a drink.");
			outputText("\n\n“<i>Mmm, please!</i>” You take care to wrap your fingers right around the can you produce, obscuring the label as you pull the ring tag off and pour into two mugs; you needn’t have bothered.  Izma all but snatches the proffered drink out of your hand and washes her food down with the golden, fizzy fluid, her attention entirely on filling her belly.  You pretend to drink from yours and watch.");
			outputText("\n\n“<i>Oh, ‘at’s good.  ‘On’t get beer ‘ery often at the lake,</i>” she says, mouth full.  She swallows and then blinks several times, as if her vision was blurring. “<i>S-strong though.</i>” Her mouth hangs open. “<i>Wh-what was in that?</i>” You grin and say nothing, waiting and watching. “<i>So… so hard to think…</i>” mumbles Izma, as her gut rumbles and her body begins to shift.  Her bikini top sags as the soft flesh of her breasts disappears; it snaps at the string as her shoulders move outwards.");
			outputText("\n\n“<i>You’ve… you’ve done something,</i>” she says, stumbling to her feet, almost falling down again as flesh visibly disappears from her thighs, every ounce of fat on her body paring off her frame. “<i>I… what have you done? Why? This is… I can’t… think…</i>” She furrows her brow in something like desperation.  You suspect she’s trying to grasp what her old intellect would have thought about this - Panic? Horror? Anger? Maybe just any spark of understanding at all- but whatever it is, it’s gone; she’s grasping for straws that have been pulled away.  When she opens her eyes again, they are unfocused, dull and intoxicated.  They also seemed to have moved further apart... ");
			outputText("\n\n“<i>Woah.  Dude,</i>” she says.  Her voice has deepened, now a mellow bass which reverberates in your bones.  A permanent lump has formed in her throat. “<i>Have you… have you got any more of that? It’s so refreshing.  It just… washes away all of those gnarly bad thoughts, doesn’t it? It just washes away </i>everything.” Without a word you pass your still full mug to Izma, and as you do so you take an inadvertent whiff of the alcoholic liquid.  You feel lightheaded as the shark morph snatches it eagerly, lifting the vessel to her mouth and gulping the brew down.  Why do you feel the urge to start chanting “CHUG! CHUG! CHUG!”? You manage to suppress it, and simply watch the incredibly potent fluid disappear down Izma’s thirsty gullet.");
			outputText("\n\nThe empty mug clatters to the ground as Izma staggers woozily.  White hair falls to the floor in chunks, leaving her with a spiky, water damaged mop.  She barely seems to notice.  The shark morph’s face clenches up in an expression somewhere between ecstasy and agony as she gropes beneath her grass skirt.  There’s a faint sucking sound as something behind her testicles disappears forever; that isn’t what’s grasped Izma’s attention, though.  The now entirely male shark morph moans lowly, sinking to his knees and clutching his dick as it grows, at least 3 more inches of cock meat pushing outwards from the base as it thickens noticeably, to the point where he can wrap his fingers around it only with difficulty.  Behind it his testicles swell, becoming the four bloated apples necessary to fuel the ridiculously massive meat pole which now swings between Izma’s legs.");
			outputText("\n\n“<i>Duuuuude,</i>” he groans, staggering to his feet again.  The transformation complete, you get up yourself and take a slow circuit around the shark morph, admiring your handiwork.  The brobrew has not gifted Izma with a massive amount of beefcake - it has instead given her a champion swimmer’s body, incredibly tight muscle dipping and rippling across his sleek frame, from his subtle abs down to his pert behind.  It is an irresistible target- you give it a light tap.  It barely even moves; you doubt there’s more than a gram of fat on his entire body.  He doesn’t even seem to have noticed you touching him.  His hands and attention are still entirely upon the monstrous thing between his legs.");
			outputText("\n\n“<i>Will you look at this thing?</i>” he says, his tone somewhere between horror and awe.  “<i>How am I going to even do anything without thinking about… all I can think about is…</i>” his expression goes vacant and his dick begins to harden, bulging with need as it becomes erect - You can practically hear the cum churning in his balls from where you are.  You suppress the urge to laugh.  Your plan has worked perfectly.  The tiger shark can no longer think beyond the dick which was so damn important to him in his previous life; in possession of more testicles than brain cells, he has become a living flesh dildo for you to manipulate as you will.");
			outputText("\n\nEventually he comes back to himself and finally notices you are standing next to him.");
			flags[kFLAGS.IZMA_BROFIED] = 1;
		}
		
	}

}